AppFile/Controllers/FileController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace AppFile.Controllers
{
    public class FileController : Controller
    {
        // GET: File
        public ActionResult Index()
        {
            var path = Server.MapPath("~/Content/Files/");
            var dir= new DirectoryInfo(path);
            var files = dir.EnumerateFiles().Select(f => f.Name);
            return View(files);
        }

        //will called while upload is clicked
        [HttpPost]
        public ActionResult Index(HttpPostedFileBase file)
        {
            var path = Path.Combine(Server.MapPath("~/Content/Files/"), file.FileName);
            var data = new byte[file.ContentLength];
            file.InputStream.Read(data, 0, file.ContentLength);
            using (var sw = new FileStream(path, FileMode.Create))
            {
                sw.Write(data, 0, data.Length);
            }
            return RedirectToAction("Index");
        }



    }
}

AppFile/Views/File/Index.cshtml
@model IEnumerable<string>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Files</h2>

<ul>
    @foreach (var fileName in Model)
    {
        var name = fileName;
        var link = @Url.Content("~/Content/Files/") + name.Replace(" ", "%20");

        <li>
            <a href="@link">@name</a>
        </li>
    }
    
   
</ul>

<div> @using (Html.BeginForm("Index", "File", FormMethod.Post, new { enctype =
          "multipart/form-data" }))
      {
          <input type="File" name="file" id="file" value="Choose File" />
          <button type="submit">Upload</button>
      }
</div>